version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
      - image: redis
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: api_test

    working_directory: /go/src/github.com/golangci/golangci-api
    steps:
      - checkout
      - run: GO111MODULE=on go mod vendor
      - run: go get github.com/golangci/golangci-lint/cmd/golangci-lint
      - run: make prepare_test_env
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: make test
